bulk-lookup: add vintage and total years to table
burningmantech/ranger-clubhouse-web pull request #1465
Opened 2022-10-31 23:58 UTC by srabraham

For https://github.com/burningmantech/ranger-clubhouse-web/issues/1140

2022-11-03 01:28 UTC, flwyd requested changes
I'm not sure why the presubmit github actions aren't running; I'll look into it.

2022-11-03 01:28 UTC, flwyd commented on app/controllers/admin/bulk-lookup.js
> +  {title: 'Vintage', key: 'vintage'},
If you add `yesno: true` the CSV export will get Y and N values.

2022-11-04 22:09 UTC, srabraham commented on app/controllers/admin/bulk-lookup.js
> +  {title: 'Vintage', key: 'vintage'},
Done, in https://github.com/burningmantech/ranger-clubhouse-web/pull/1466

2022-11-04 22:09 UTC, srabraham commented
Moving this PR to https://github.com/burningmantech/ranger-clubhouse-web/pull/1466, which is a PR in this repo, rather than from a different forked one

2022-11-04 22:09 UTC, closed without merging