Get trainer report positions from new position table column
burningmantech/ranger-clubhouse-web pull request #1473
Opened 2022-11-11 16:23 UTC by srabraham

There's a corresponding ranger-clubhouse-api change that should be merged first.

There are probably rough edges here, so give me whatever feedback is relevant. I also haven't updated
any tests, but I'll do so if you point me to tests that ought to be updated.

https://github.com/burningmantech/ranger-clubhouse-web/issues/1471

2022-11-11 16:25 UTC, srabraham commented on app/templates/training/session/trainers-report.hbs
> +    {{/each}}
I'm very open to suggestion on this. It seemed like overkill to display this stuff as a table

2022-11-11 18:47 UTC, mikeburg requested changes

2022-11-11 18:47 UTC, mikeburg commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
A few things here -

1) Use ```<h3 class="d-print-page-break">Teams Legend</h3>``` to set the page title. The "Teams Legend" with a line  It's not a data term in a list of other data terms. The h3 tag is only a suggestion - h1 or h2 might look better on the page.

2) The paragraph tag (```<p>```) is best used when you want to start a block AND have a bottom margin between the contents in the paragraph and the following block/section.  

3) The dt & dd tag have to be wrapped with the dl tag to be syntactically  / semantically correct HTML. Weird rendering errors may happen on different browser if you don't.

4) The use case for dt/dd is when multiple data terms & definitions are listed.  In this case, it's very appropriate to use the data tags when listing each short title with it's definition. Like this -
```
<dl>
{{#each this.teams_names as |team|}}
  <dt>{{team.short_title}}</dt>
  <dd>{{team.title}}</dd>
{{/each}
</dl>
```

An alternative way is to use a simple table in place of dl/dt/dd.

The bootstrap CSS framework is the underpinnings of the entire Clubhouse CSS layout/styles. See the bootstrap page on lists for different rendering options:
https://getbootstrap.com/docs/5.2/content/reboot/#lists

2022-11-11 18:47 UTC, mikeburg commented on app/templates/admin/positions.hbs
> +          <BooleanIcon @value={{position.on_trainer_report}} @trueIcon="list"/>
Try to avoid reusing the same icon as the On SL Report column. rectange-list might be good. The icons are provided through fontawesome.com -- be sure to select the 'free' tag when browsing for available options. The pro icons are not available since we want to continue to be open sourced.

2022-11-11 21:54 UTC, srabraham commented on app/templates/admin/positions.hbs
> +          <BooleanIcon @value={{position.on_trainer_report}} @trueIcon="list"/>
Works for me. Thanks for the heads-up about needing to pick free icons

2022-11-11 22:28 UTC, srabraham commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
Thanks for all that, especially for teaching me about "dl" (this is my first time writing a dl/dt/dd). I think I have this in a reasonable place now. Any thoughts on having that text after the legend ahead of it instead, i.e. so that it would print on the same page as the trainee list?

![image](https://user-images.githubusercontent.com/23407555/201439420-74ca5b46-517c-42ea-ad95-fd5bb75ec2ba.png)

2022-11-11 23:15 UTC, mikeburg commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
The trainee list can vary greatly depending on how many sign ups there are and the type of trainees (vets, binaries & auditors). The list may span two pages in which case the legend will be only be one page (See the NYC May 14th, 2022 training as an example.) The other scenario is where the legend is split between the bottom of the page and the top of the next one.  Either way, we want to force a page break so the legend can be used easily.

2022-11-11 23:42 UTC, srabraham commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
I should clarify, as I worded my comment kind of clumsily. I think the page break is a good idea. My question is whether the preexisting two "p" blocks should go above the legend or remain below

![image](https://user-images.githubusercontent.com/23407555/201444652-aaba3e51-7415-4568-bd18-09a741eb7be7.png)

2022-11-12 00:50 UTC, mikeburg commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
Oh right, sorry -- yes, by all means move two paragraphs up. Actually, move the second paragraph about the inactive/retired Rangers to above the trainee listing. Several trainers last event cycle failed to email let a couple of inactive/retirees know they had to take the full day's training.

2022-11-12 01:41 UTC, srabraham commented on app/templates/training/session/trainers-report.hbs
> +    <dt>Teams legend</dt>
Sounds good. Done

2022-11-12 04:23 UTC, merged